version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  database:
    image: postgres:16
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: covid-db
      POSTGRES_PASSWORD: covid-db
      POSTGRES_DB: covid-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U covid-db"]
      interval: 10s
      timeout: 5s
      retries: 3

    
